apiVersion: v1
kind: ConfigMap
metadata:
 name: {{ .Release.Name }}-configmap
 namespace: {{ .Release.Namespace }}
 labels:
    {{- include "labels" . |indent 4 }}
    {{- if .Values.commonLabels }}
    {{- tpl (toYaml .Values.commonLabels) $ |nindent 4 }}
    {{- end }}

data:
 gencsv.sh: |+
    {{ .Files.Get "gencsv.sh" | nindent 4 }}
 {{- if eq .Values.prometheus.enabled true }}
 prometheus.yml: |+
    global:
      {{- if .Values.prometheus.scrapeInterval }}
      scrape_interval: {{ .Values.prometheus.scrapeInterval }}
      {{- else }}
      scrape_interval:     15s
      {{- end }}
      {{- if .Values.prometheus.evaluationInterval }}
      evaluation_interval: {{ .Values.prometheus.evaluationInterval }}
      {{- else }}
      evaluation_interval: 15s
      {{- end }}
    scrape_configs:
     - job_name: 'prometheus'
       static_configs:
          - targets: ['localhost:9090']
     - job_name: 'csvserver'
       static_configs:
          {{- if .Values.service.port }}
          - targets: ['{{ .Release.Name }}-service:{{ .Values.service.port }}']
          {{- else }}
          - targets: ['{{ .Release.Name }}-service:9300']
          {{- end }}
  {{- end }}
