apiVersion: v1
kind: ConfigMap
metadata:
 name: {{ .Release.Name }}-configmap
 labels:
    {{- include "labels" . |indent 4 }}
    {{- if .Values.commonLabels }}
    {{- tpl (toYaml .Values.commonLabels) $ |nindent 4 }}
    {{- end }}

data:
 gencsv.sh: |+
    {{ .Files.Get "gencsv.sh" | nindent 4 }}
