apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-deploy-delete-role
  namespace: {{ .Release.Namespace }}
  annotations:
     helm.sh/hook: pre-upgrade
     helm.sh/hook-delete-policy: hook-succeeded
     helm.sh/hook-weight: "-4"
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - list
      - get
      - delete
    resourceNames:
      - {{ .Release.Name }}-csvserver
  - apiGroups:
     - rbac.authorization.k8s.io
    resources:
      - role
      - rolebinding
    resourceNames:
       - {{ .Release.Name }}-deploy-delete-role
       - {{ .Release.Name }}-deploy-delete-rolebinding
    verbs:
      - list 
      - get
      - delete
