apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-deploy-delete-rolebinding
  namespace: {{ .Release.Namespace }}
  annotations:
      helm.sh/hook: pre-upgrade
      helm.sh/hook-delete-policy: hook-succeeded
      helm.sh/hook-weight: "-3"
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-deploy-delete-role
  apiGroup: rbac.authorization.k8s.io
