apiVersion: v1
kind: Service
metadata:
 namespace: {{ .Release.Namespace }}
 name: {{ .Release.Name }}-service
 labels:
    {{- include "labels" . |indent 4 }}
    {{- if .Values.commonLabels }}
    {{- tpl (toYaml .Values.commonLabels) $ |nindent 4 }}
    {{- end }}
spec:
 selector:
    {{- include "labels" . |indent 4 }}
    {{- if .Values.commonLabels }}
    {{- tpl (toYaml .Values.commonLabels) $ |nindent 4 }}
    {{- end }}
 {{- if .Values.service.type }}
 type: {{ .Values.service.type }}
 {{- else }}   
 type: ClusterIP
 {{- end }}
 ports:
   {{- if .Values.service.port }}
   - port: {{ .Values.service.port }}
   {{- else }}
   - port: 9300
   {{- end }}
     targetPort: 9300
